version: "3.8"
services:
  server:
    build: .
    restart: always
    ports: 
      - 8081:8081
    depends_on:
      - mysqldb
  mysqldb:
    image: "mysql:5.7"
    restart: always
    ports:
      - 3307:3306
    environment:
      MYSQL_DATABASE: devops
      MYSQL_PASSWORD: root
      MYSQL_ROOT_PASSWORD: root
    volumes:
      - mysqldb_data:/var/lib/mysql

volumes:
  mysqldb_data:
